In [21]:
import xarray as xr
from datetime import datetime
import numpy as np

from climpy.hazard.condition import MaskArea, AverageArea, ThresholdPercentile, ConnectStructure
from climpy.hazard.criterion import PointHazardCriterion
from climpy.hazard.event import PointHazard

In [22]:
shp_file = "/data/compoundx/GRDC_runoff/Xie_bnd/individual_shp/3634110.geojson"
input_dir = '/data/compoundx/causal_flood/grdc/GRDC-Daily.nc'

In [26]:
runoff = xr.open_dataset(input_dir)["runoff_mean"].sel(id = 6337060)

In [32]:
runoff

<xarray.DataArray 'runoff_mean' (time: 78915)>
array([nan, nan, nan, ..., nan, nan, nan], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 1806-01-01 1806-01-02 ... 2022-01-22
    id       int32 6337060
Attributes:
    units:      m3/s
    long_name:  Mean daily discharge (Q)

In [34]:
quantile = 0.9
structure = np.array([1,1,1])
flood_criterion = PointHazardCriterion([ThresholdPercentile('>', quantile),
                                       ConnectStructure(structure)])

In [35]:
flood = PointHazard(criterion = flood_criterion)
flood.apply_criterion(runoff)

()
<xarray.DataArray 'runoff_mean' (time: 78915)>
array([nan, nan, nan, ..., nan, nan, nan], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 1806-01-01 1806-01-02 ... 2022-01-22
    id       int32 6337060
Attributes:
    units:      m3/s
    long_name:  Mean daily discharge (Q)


In [38]:
flood.get_event(32)

Areal Hazard Event:
    * Temporal Extent: 1965-04-28 00:00:00 to 1965-05-01 00:00:00

In [4]:

ma = MaskArea(germany_shp)
x = ma(mhmOutput)
aa = AverageArea()
x = aa(x)

(array([1]),)